spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/im-core?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: root

  application:
    name: im-core

# logger 配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000

im-server:
  zkServers: 8.134.134.68:2181
  connectionTimeout: 5000
  loadBalanceStrategy: 3 #负载均衡策略 1-随机 2-轮询 3-一致性哈希
  consistentHashAlgorithm: 1 #1-使用TreeMap实现一致性哈希算法
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql